<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Assignments have been updated' => '指派權限更新成功',
    'Auth item with such name already exists' => '權限項目已經存在',
    'Children' => '子層',
    'Class "{0}" does not exist' => 'Class "{0}" 不存在',
    'Create' => '新增',
    'Create new permission' => '新增權限',
    'Create new role' => '新增角色',
    'Description' => '描述',
    'Invalid value' => 'ˊ無效數值',
    'Item has been created' => '權限項目已經新增',
    'Item has been updated' => '權限項目已經更新',
    'Items' => '權限項目',
    'Name' => '名稱',
    'New permission' => '新增權限項目',
    'New role' => '新增角色',
    'New user' => '新增使用者',
    'Permissions' => '許可權限',
    'Roles' => '角色',
    'Rules' => '規則',
    'Rule class can not be instantiated' => 'Die Regelklasse kann nicht instanziiert werden',
    'Rule class must extend "yii\rbac\Rule"' => 'Die Regelklasse muss "yii\rbac\Rule" erweitern',
    'Rule name' => 'Regelname',
    'Save' => 'Speichern',
    'There is neither role nor permission with name "{0}"' => 'Es gibt weder eine Regel noch eine Berechtigung mit dem Namen "{0}"',
    'Update assignments' => '更新權限角色',
    'Update permission' => '更新權限項目',
    'Update role' => '更新角色',
    'Users' => '使用者',
];
